{
 "title": "bi-mq-monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channelsTotal", "legendFormat": "channelsTotal {{host}}" },
    { "expr": "rabbitmq_connectionsTotal", "legendFormat": "connectionsTotal  {{host}}" },
    { "expr": "rabbitmq_consumersTotal", "legendFormat": "consumersTotal {{host}}" },
    { "expr": "rabbitmq_queuesTotal", "legendFormat": "queuesTotal {{host}}" },
    { "expr": "rabbitmq_exchangesTotal", "legendFormat": "exchangesTotal  {{host}}" },
    { "expr": "rabbitmq_queue_messages_total", "legendFormat": "queue_messages_total {{host}}" },
    {
     "expr": "rabbitmq_queue_messages_ready_total",
     "legendFormat": "queue_messages_ready_total {{host}}"
    },
    {
     "expr": "queue_messages_unacknowledged_total",
     "legendFormat": "messages_unacknowledged_total {{host}}"
    }
   ]
  },
  {
   "title": "queue_messages_delivered_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  },
  {
   "title": "exchange_messages_published_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_exchange_messages_published_in_total",
     "legendFormat": "{{host}}{{vhost}}"
    }
   ]
  },
  {
   "title": "rabbitmq_queue_messages_get_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_get_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}\t",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  },
  {
   "title": "queue_messages_redelivered_total",
   "type": "graph",
   "description": "Count of subset of messages in deliver_get which had the redelivered flag set.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_redelivered_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}\t",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  },
  {
   "title": "queue_messages_delivered_noack_total",
   "type": "graph",
   "description": "Count of messages delivered in acknowledgement mode to consumers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_noack_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  },
  {
   "title": "queue_messages_returned_total",
   "type": "graph",
   "description": "Count of messages returned to publisher as unroutable.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_returned_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}\t",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  },
  {
   "title": "queue_messages_get_noack_total",
   "type": "graph",
   "description": "Count of messages delivered in no-acknowledgement mode in response to basic.get.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_get_noack_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}\t",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  },
  {
   "title": "rabbitmq_queue_messages_confirmed_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_confirmed_total{group=\"rabbitmq\",host=\"192.168.165.112\",instance=\"im-192.168.166.66\",job=\"rabbitmq\"}",
     "legendFormat": "vhost:{{vhost}}-queue:{{queue}}"
    }
   ]
  }
 ]
}