{
 "title": "Traefik测试环境图像",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Total requests over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_backend_requests_total{instance=\"192.168.165.69:8580\",job=\"traefik-test\"}",
     "legendFormat": "{{backend}}:{{code}}"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{code=\"200\"}[5m])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "统计5分钟内平均4xx 5xx错误",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{code!=\"200\",code!=\"304\",code!=\"307\",code!=\"302\",code!=\"206\"}[5m])",
     "legendFormat": "{{backend}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{service !~ \"http|https\"}[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{service =~ \"http|https\"}[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}